// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkezyRTBAd9R8VCiRWXnPPJG9ZWWGdb4',
    appId: '1:1049840318668:web:5499b964f2fd20fff3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    authDomain: 'property-c1175.firebaseapp.com',
    databaseURL: 'https://property-c1175-default-rtdb.firebaseio.com',
    storageBucket: 'property-c1175.appspot.com',
    measurementId: 'G-W3D6769KG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_XJAVcmbPeWfT00hPKRiYp28NY6Q7K0o',
    appId: '1:1049840318668:android:aed511e8896dd720f3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    databaseURL: 'https://property-c1175-default-rtdb.firebaseio.com',
    storageBucket: 'property-c1175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxqMV9bRvp4URNFvns4HxHLPSVLYrgbw',
    appId: '1:1049840318668:ios:b57aec53e7508aeef3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    databaseURL: 'https://property-c1175-default-rtdb.firebaseio.com',
    storageBucket: 'property-c1175.appspot.com',
    androidClientId: '1049840318668-s2olv5t2ta0emghotu5cb3mto4pecql0.apps.googleusercontent.com',
    iosBundleId: 'com.example.baytiai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxqMV9bRvp4URNFvns4HxHLPSVLYrgbw',
    appId: '1:1049840318668:ios:b57aec53e7508aeef3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    databaseURL: 'https://property-c1175-default-rtdb.firebaseio.com',
    storageBucket: 'property-c1175.appspot.com',
    androidClientId: '1049840318668-s2olv5t2ta0emghotu5cb3mto4pecql0.apps.googleusercontent.com',
    iosBundleId: 'com.example.baytiai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtkezyRTBAd9R8VCiRWXnPPJG9ZWWGdb4',
    appId: '1:1049840318668:web:dede60249a43cf0df3aa69',
    messagingSenderId: '1049840318668',
    projectId: 'property-c1175',
    authDomain: 'property-c1175.firebaseapp.com',
    databaseURL: 'https://property-c1175-default-rtdb.firebaseio.com',
    storageBucket: 'property-c1175.appspot.com',
    measurementId: 'G-D81FRF5LB4',
  );

}